name: Build and Deploy

on:
  push:
    branches-ignore:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      # Use a Jekyll image that includes Ruby 2.7 and is compatible with Jekyll 4.3 and jekyll-scholar.
      # If "jekyll/jekyll:4.3" is unavailable, "jekyll/jekyll:latest" can be used.
      image: jekyll/jekyll:4.3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: bundle install

      - name: Build Jekyll Site
        run: bundle exec jekyll build

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}